site_name: Introduction to modern software engineering practices
repo_url: https://github.com/QuTech-Delft/imsep

theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tracking
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - tables
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search

nav:
  - Home:
      - index.md
  - Software development:
      - software-development/index.md
  - Version control:
      - version-control/index.md
      - Basic development cycle: version-control/basic-cycle.md
      - Advanced development cycle: version-control/advanced-cycle.md
  - Dependency management:
      - dependencies/index.md
  - Clean code:
      - clean-code/index.md
      - An introduction to testing: clean-code/basic-testing.md
      - Advanced testing methods: clean-code/advanced-testing.md
